name: encryption
description: A simple Flutter plugin to encrypt and decrypt a string.
version: 0.0.1
author: Aubrey Malabie  <aubrey@aftarobot.com>
homepage: https://github.com/bohatmx/flutter-encryption-plugin

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.oneconnect.encryption
    pluginClass: EncryptionPlugin
